
import type { Metadata } from "next";

import "./globals.css";
import I18nProvider from "./i18nProvider";


import localFont from "next/font/local";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const droidArabicKufi = localFont({
  src: [ 
    { path: "./fonts/NotoKufiArabic-Black.ttf", weight: "900", style: "normal" },
    { path: "./fonts/NotoKufiArabic-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "./fonts/NotoKufiArabic-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/NotoKufiArabic-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/NotoKufiArabic-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/NotoKufiArabic-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/NotoKufiArabic-Light.ttf", weight: "300", style: "normal" },
    { path: "./fonts/NotoKufiArabic-Thin.ttf", weight: "200", style: "normal" },
    { path: "./fonts/NotoKufiArabic-ExtraLight.ttf", weight: "100", style: "normal" },

  ],
  variable: "--font-droid-kufi",
});


const helvetica = localFont({
  src: [
    { path: "../app/fonts/helvetica-black.otf", weight: "900", style: "normal" },
    { path: "../app/fonts/Helvetica-Bold.ttf", weight: "700", style: "normal" },
    { path: "../app/fonts/helvetica-light.ttf", weight: "200", style: "normal" },
    { path: "../app/fonts/Helvetica.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Server-rendered defaults for `lang` and `dir` attributes
  const defaultLanguage: string = "ar"; // You can replace this with a server-side value
  const dir = defaultLanguage === "ar" ? "rtl" : "ltr";

  const fontStyles = `${droidArabicKufi.variable} ${helvetica.variable} sans-serif`;


  return (
    <html lang={defaultLanguage} dir={dir} className={fontStyles}>
      <body >
        <I18nProvider>
          <Header/>
          {children}
          <Footer/> 
          </I18nProvider>
      </body>
    </html>
  );
}
