
import type { Metadata } from "next";

import "./globals.css";
import I18nProvider from "./i18nProvider";




export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Server-rendered defaults for `lang` and `dir` attributes
  const defaultLanguage: string = "en"; // You can replace this with a server-side value
  const dir = defaultLanguage === "ar" ? "rtl" : "ltr";




  return (
    <html lang={defaultLanguage} dir={dir}>
      <body >
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
